version: '3'

services:
  keymanagergrpc:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "50051:50051"
    depends_on:
        - postgres
        - bcb
        - erp-itau
    environment:
      DB_URL: jdbc:postgresql://postgres/pix
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DIALECT: POSTGRES
      BCB_URL: http://bcb:8082/api/v1/pix/keys
      ITAU:URL: http://erp-itau:9091/api/v1/clientes


  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082

  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pix
      POSTGRES_HOST: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: